rootProject.name = 'mail-demo-36078853'

gradle.allprojects { project ->
    project.afterEvaluate {
        project.dependencies {
            implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.2'
            implementation 'org.postgresql:postgresql:42.7.1'
            implementation 'org.flywaydb:flyway-core:10.8.1'
            implementation 'org.flywaydb:flyway-database-postgresql:10.8.1'
        }
    }
}
