spring.datasource.url=jdbc:postgresql://ep-wild-king-aikhd2vf-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_x9PpcrK3DugS&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

aws.s3.bucket=dummy-bucket
